// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWeyxRVnVDvjegHyEVTkF-MPyWmEhLK8o',
    appId: '1:1060173404019:web:bd59b142987dc73c029706',
    messagingSenderId: '1060173404019',
    projectId: 'project-banknagari-f28db',
    authDomain: 'project-banknagari-f28db.firebaseapp.com',
    storageBucket: 'project-banknagari-f28db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIscnH0WIR-HqZ4pWUGgualNYUA9uWkRY',
    appId: '1:1060173404019:android:127841b937880366029706',
    messagingSenderId: '1060173404019',
    projectId: 'project-banknagari-f28db',
    storageBucket: 'project-banknagari-f28db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK0aRFsQN-_IPniybeITi6b0DQ6SbSJts',
    appId: '1:1060173404019:ios:08041a9856b29cbb029706',
    messagingSenderId: '1060173404019',
    projectId: 'project-banknagari-f28db',
    storageBucket: 'project-banknagari-f28db.appspot.com',
    iosBundleId: 'com.example.aplikasiNagaricare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK0aRFsQN-_IPniybeITi6b0DQ6SbSJts',
    appId: '1:1060173404019:ios:08041a9856b29cbb029706',
    messagingSenderId: '1060173404019',
    projectId: 'project-banknagari-f28db',
    storageBucket: 'project-banknagari-f28db.appspot.com',
    iosBundleId: 'com.example.aplikasiNagaricare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWeyxRVnVDvjegHyEVTkF-MPyWmEhLK8o',
    appId: '1:1060173404019:web:b01115224938e5ee029706',
    messagingSenderId: '1060173404019',
    projectId: 'project-banknagari-f28db',
    authDomain: 'project-banknagari-f28db.firebaseapp.com',
    storageBucket: 'project-banknagari-f28db.appspot.com',
  );
}
